### ISSUE TITLE
Survival estimates at time points on KM curves

### ISSUE THREAD

**Issue by Mahrefat** [VincentAlcazer/StatAid#5]
Reporting survival estimates at time points on KM curves. Eg 2 and 5 year OS and PFS , with 95% CI and p values.
Thank you!

**Comment by VincentAlcazer** [comment]
Hi @Mahrefat , thank you for your suggestion. 

This is a very good point that was a work in progress until now: all the survival estimates can now be found for each time point in the new "survival table" tab!

Please let me know if anything is not working as expected.

**Comment by Mahrefat** [comment]
Thank you so much! I was able to access it. This is great! I will tweet about it. Please keep up the good work!
MG

From: Vincent Alcazer ***@***.***>
Date: Tuesday, July 12, 2022 at 4:02 PM
To: VincentAlcazer/StatAid ***@***.***>
Cc: Mahrefat ***@***.***>, Mention ***@***.***>
Subject: Re: [VincentAlcazer/StatAid] Survival estimates at time points on KM curves (Issue #5)

Hi @Mahrefat<https://github.com/Mahrefat> , thank you for your suggestion.

This is a very good point that was a work in progress until now: all the survival estimates can now be found for each time point in the new "survival table" tab!

Please let me know if anything is not working as expected.
